version: "3.3"

services:
  server:
    container_name: films-caddy
    image: caddy:alpine
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.fdpa.rule: Host(`films.localhost`)

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    external:
      name: proxy
