version: "3.3"

services:
  server:
    container_name: fdpa-caddy
    image: caddy:alpine
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.fdpa.rule: Host(`fdpa.freelooser.net`)
      traefik.http.routers.fdpa.entrypoints: web

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    external:
      name: proxy